### ISSUE TITLE
Integrate shotgun?

### ISSUE THREAD

**Issue by kedarmhaswade** [dmarcotte/github-markdown-preview#37]
Is it worthwhile for github-markdown-preview (standalone usage) to identify file-save events and regenerate the preview? I can contribute it if there is interest.

**Comment by kedarmhaswade** [comment]
I usually am careful about rookie errors, but I did commit this one. Apologies. Works well with listen. :+1:

**Comment by dmarcotte** [comment]
No worries!  Glad it's working well for you.  Thanks for the note, and let me know if you run any issues.
