### ISSUE TITLE
uninitialized constant GitHub (NameError)

### ISSUE THREAD

**Issue by wurde** [dmarcotte/github-markdown-preview#38]
ruby 2.2.2p95 (2015-04-13 revision 50295) [i686-linux]

**Comment by dmarcotte** [comment]
Hey @wurde, check out the workaround for this here: https://github.com/dmarcotte/github-markdown-preview/issues/35 (you may be on the wrong version, or may need to reinstall some gems).

Hopefully that rights the ship for you, and if you get any insight into what dependency issue caused this, please let me know!  Seems like a pain to have folks reinstalling a bunch of gems.
